#!/usr/bin/perl -w
# This script creates the symlinks needed by this RPM
# Specific support exists to create symlinks within e-smith web "panels"
# and for links from named "events" directories into the "actions" directory

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
# functions for manager panel
#--------------------------------------------------
my $panel = "manager";

panel_link("raidstatus", $panel);

#--------------------------------------------------
# actions for console-save event:
#--------------------------------------------------



#--------------------------------------------------
# Link for shell template:
#--------------------------------------------------


#--------------------------------------------------
# The End
#--------------------------------------------------
