#!/usr/bin/perl -wT

#----------------------------------------------------------------------
# heading     : Administration
# description : Raid Status
# navigation  : 3100 3200
#
# Authors: Stephane de Labrusse
#----------------------------------------------------------------------

use strict;
use warnings;

use esmith::FormMagick::Panel::raidstatus;

my $f = esmith::FormMagick::Panel::raidstatus->new();
$f->display();

__DATA__
<form
    title="FORM_TITLE"
        header="/etc/e-smith/web/common/head.tmpl"
	footer="/etc/e-smith/web/common/foot.tmpl">
 	
	<page name="First" pre-event="print_status_message()"   post-event="apply()">
		<description>DESCRIPTION_RAIDSTATUS</description>
        	<subroutine src="print_raidstatus()" />

             <field type="text" id="mailto" size="80">
                <label>MAILTO</label>
             value="get_prop('mailto')">
             <description>DESC_MAILTO</description>
              <label>MAILTO</label>
              </field>

 <subroutine src="print_button('SAVE')" />
	</page>

</form>

